services:
    minecraft-server:
        image: itzg/minecraft-server
        container_name: minecraft-server
        environment:
            EULA: "true"
            MEMORY: 4G # recommended amount of dedotated wam is 4G
            # VERSION: "1.18.1" # Specify version
        ports:
            - "25565:25565"
        volumes:
            - ./server-data:/data
        stdin_open: true
        tty: true
        restart: unless-stopped